/**
 * Invoice API Route
 * CRUD operations for invoices with Supabase persistence.
 *
 * GET  /api/invoices          - List all invoices (with optional filters)
 * POST /api/invoices          - Create or update (upsert) an invoice
 * PUT  /api/invoices          - Update invoice status or fields
 * DELETE /api/invoices?id=xyz - Delete an invoice
 */

import { NextRequest, NextResponse } from 'next/server';
import { getSupabaseAdmin } from '@/lib/supabase';
import { requireAdminAuth, requirePermission } from '@/lib/admin-auth-middleware';
import { createInvoiceSchema, updateInvoiceSchema, validateBody } from '@/lib/validations/schemas';
import { notifyTeam, invoiceCreatedEmail, notifyRecipient, invoiceStatusEmail } from '@/lib/email/send';
import { notifyClient } from '@/lib/notifications';
import { logAuditEvent, getClientIP } from '@/lib/admin/audit-log';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const SELECT_COLS = [
  'id', 'invoice_number', 'client_id', 'client_name', 'client_email',
  'client_phone', 'client_address', 'client_city', 'client_state',
  'client_country', 'client_gst_number', 'date', 'due_date', 'subtotal',
  'tax_rate', 'tax_amount', 'tax', 'total', 'status', 'line_items',
  'notes', 'terms', 'currency', 'cgst_amount', 'sgst_amount', 'igst_amount',
  'place_of_supply', 'company_gstin', 'created_at', 'updated_at',
  'auto_generated',
].join(', ');

/** Transform a Supabase row (snake_case) → API response (camelCase) */
function transformInvoice(row: Record<string, unknown>) {
  return {
    id: row.id,
    invoiceNumber: row.invoice_number,
    date: row.date,
    dueDate: row.due_date,
    client: {
      id: row.client_id || '',
      name: row.client_name || '',
      email: row.client_email || '',
      phone: row.client_phone || '',
      address: row.client_address || '',
      city: row.client_city || '',
      state: row.client_state || '',
      country: row.client_country || 'India',
      gstNumber: row.client_gst_number || '',
    },
    lineItems: row.line_items || [],
    subtotal: Number(row.subtotal) || 0,
    taxRate: Number(row.tax_rate) || 18,
    taxAmount: Number(row.tax_amount) || Number(row.tax) || 0,
    total: Number(row.total) || 0,
    currency: (row.currency as string) || 'INR',
    cgstAmount: Number(row.cgst_amount) || 0,
    sgstAmount: Number(row.sgst_amount) || 0,
    igstAmount: Number(row.igst_amount) || 0,
    placeOfSupply: (row.place_of_supply as string) || '',
    companyGstin: (row.company_gstin as string) || '23BQNPM3447F1ZT',
    notes: row.notes || '',
    terms: row.terms || '',
    status: row.status || 'draft',
    autoGenerated: !!row.auto_generated,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

/** Build Supabase record from request body */
function buildRecord(body: Record<string, unknown>) {
  const client = (body.client || {}) as Record<string, unknown>;

  return {
    id: (body.id as string) || `inv-${Date.now()}`,
    invoice_number: body.invoiceNumber as string,
    date: body.date as string,
    due_date: body.dueDate as string,
    client_id: (client.id as string) || (body.clientId as string) || '',
    client_name: (client.name as string) || (body.clientName as string) || '',
    client_email: (client.email as string) || '',
    client_phone: (client.phone as string) || '',
    client_address: (client.address as string) || '',
    client_city: (client.city as string) || '',
    client_state: (client.state as string) || '',
    client_country: (client.country as string) || 'India',
    client_gst_number: (client.gstNumber as string) || '',
    line_items: body.lineItems || [],
    subtotal: parseFloat(String(body.subtotal)) || 0,
    tax_rate: parseFloat(String(body.taxRate)) || 18,
    tax_amount: parseFloat(String(body.taxAmount)) || 0,
    tax: parseFloat(String(body.taxAmount)) || 0,
    total: parseFloat(String(body.total)) || 0,
    notes: (body.notes as string) || '',
    terms: (body.terms as string) || '',
    status: (body.status as string) || 'draft',
    currency: (body.currency as string) || 'INR',
    cgst_amount: parseFloat(String(body.cgstAmount)) || 0,
    sgst_amount: parseFloat(String(body.sgstAmount)) || 0,
    igst_amount: parseFloat(String(body.igstAmount)) || 0,
    place_of_supply: (body.placeOfSupply as string) || '',
    company_gstin: (body.companyGstin as string) || '23BQNPM3447F1ZT',
    updated_at: new Date().toISOString(),
  };
}

// ---------------------------------------------------------------------------
// GET - List invoices
// ---------------------------------------------------------------------------

export async function GET(request: NextRequest) {
  const auth = await requirePermission(request, 'finance.read');
  if ('error' in auth) return auth.error;

  try {
    const { searchParams } = new URL(request.url);
    const singleId = searchParams.get('id');

    // Single invoice fetch by ID
    if (singleId) {
      const supabase = getSupabaseAdmin();
      const { data, error } = await supabase
        .from('invoices')
        .select(SELECT_COLS)
        .eq('id', singleId)
        .single();
      if (error || !data) {
        return NextResponse.json({ success: false, error: 'Invoice not found' }, { status: 404 });
      }
      return NextResponse.json({ success: true, data: transformInvoice(data as unknown as Record<string, unknown>) });
    }

    const clientId = searchParams.get('clientId');
    const status = searchParams.get('status');
    const search = searchParams.get('search');

    // Pagination: only active when `page` param is provided (backwards compat)
    const pageParam = searchParams.get('page');
    const isPaginated = pageParam !== null;
    const page = Math.max(1, parseInt(pageParam || '1', 10));
    const pageSize = Math.max(1, Math.min(100, parseInt(searchParams.get('pageSize') || '25', 10)));

    const supabase = getSupabaseAdmin();

    /** Apply shared filters to a query builder */
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    function applyFilters(q: any) {
      if (clientId) q = q.eq('client_id', clientId);
      if (status) q = q.eq('status', status);
      if (search) {
        q = q.or(
          `invoice_number.ilike.%${search}%,client_name.ilike.%${search}%`,
        );
      }
      return q;
    }

    let data;
    let totalItems = 0;

    if (isPaginated) {
      // Get total count with same filters
      const { count, error: countError } = await applyFilters(
        supabase.from('invoices').select('*', { count: 'exact', head: true })
      );
      if (countError) throw countError;
      totalItems = count || 0;

      // Paginated data
      const from = (page - 1) * pageSize;
      const to = from + pageSize - 1;
      let query = applyFilters(
        supabase.from('invoices').select(SELECT_COLS)
      );
      query = query.order('created_at', { ascending: false });
      query = query.range(from, to);
      const result = await query;
      if (result.error) throw result.error;
      data = result.data;
    } else {
      let query = applyFilters(
        supabase.from('invoices').select(SELECT_COLS)
      );
      query = query.order('created_at', { ascending: false });
      const result = await query;
      if (result.error) throw result.error;
      data = result.data;
    }

    const invoices = ((data || []) as unknown as Record<string, unknown>[]).map(transformInvoice);

    // Summary stats
    const stats = {
      total: isPaginated ? totalItems : invoices.length,
      draft: invoices.filter(i => i.status === 'draft').length,
      sent: invoices.filter(i => i.status === 'sent').length,
      paid: invoices.filter(i => i.status === 'paid').length,
      overdue: invoices.filter(i => i.status === 'overdue').length,
      totalOutstanding: invoices
        .filter(i => i.status === 'sent' || i.status === 'overdue')
        .reduce((s, i) => s + i.total, 0),
      totalPaid: invoices
        .filter(i => i.status === 'paid')
        .reduce((s, i) => s + i.total, 0),
    };

    const responseBody: Record<string, unknown> = { success: true, data: invoices, stats };

    if (isPaginated) {
      responseBody.pagination = {
        page,
        pageSize,
        totalItems,
        totalPages: Math.ceil(totalItems / pageSize),
      };
    }

    return NextResponse.json(responseBody);
  } catch (error) {
    console.error('Error fetching invoices:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to fetch invoices' },
      { status: 500 },
    );
  }
}

// ---------------------------------------------------------------------------
// POST - Create or upsert invoice
// ---------------------------------------------------------------------------

export async function POST(request: NextRequest) {
  const auth = await requirePermission(request, 'finance.write');
  if ('error' in auth) return auth.error;

  try {
    const rawBody = await request.json();
    const validation = validateBody(createInvoiceSchema, rawBody);
    if (!validation.success) {
      return NextResponse.json({ success: false, error: validation.error }, { status: 400 });
    }
    const body = rawBody;
    const record = buildRecord(body);

    const supabase = getSupabaseAdmin();

    // Upsert: if id exists, update; otherwise insert
    const { error } = await supabase
      .from('invoices')
      .upsert(record, { onConflict: 'id' });

    if (error) throw error;

    // Fire-and-forget email notification
    const emailData = invoiceCreatedEmail({
      invoiceNumber: record.invoice_number,
      clientName: record.client_name,
      total: record.total,
      currency: record.currency || 'INR',
      dueDate: record.due_date,
      status: record.status,
    });
    notifyTeam(emailData.subject, emailData.html);

    // Notify client about new invoice
    if (record.client_id) {
      notifyClient(record.client_id, {
        type: 'invoice_created',
        title: 'New invoice available',
        message: `Invoice ${record.invoice_number} — ${record.client_name}`,
        priority: 'high',
        actionUrl: `/client/${record.client_id}/documents`,
      });
    }

    // Fire-and-forget audit log
    await logAuditEvent({
      user_id: auth.user.id,
      user_name: auth.user.name,
      action: 'create',
      resource_type: 'invoice',
      resource_id: record.id,
      details: { invoiceNumber: record.invoice_number, clientName: record.client_name, total: record.total },
      ip_address: getClientIP(request),
    });

    return NextResponse.json({
      success: true,
      data: { id: record.id },
      message: 'Invoice saved successfully',
    });
  } catch (error) {
    console.error('Error saving invoice:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to save invoice' },
      { status: 500 },
    );
  }
}

// ---------------------------------------------------------------------------
// PUT - Update invoice status or specific fields
// ---------------------------------------------------------------------------

export async function PUT(request: NextRequest) {
  const auth = await requirePermission(request, 'finance.write');
  if ('error' in auth) return auth.error;

  try {
    const rawBody = await request.json();
    const validation = validateBody(updateInvoiceSchema, rawBody);
    if (!validation.success) {
      return NextResponse.json({ success: false, error: validation.error }, { status: 400 });
    }
    const body = rawBody as Record<string, unknown>;
    const { invoiceId, status, ...rest } = body;

    const updates: Record<string, unknown> = {
      updated_at: new Date().toISOString(),
    };

    if (status) updates.status = status;

    // Allow partial field updates
    if (rest.notes !== undefined) updates.notes = rest.notes;
    if (rest.terms !== undefined) updates.terms = rest.terms;

    const supabase = getSupabaseAdmin();
    const { data: invoice, error } = await supabase
      .from('invoices')
      .update(updates)
      .eq('id', invoiceId)
      .select('id, invoice_number, client_id, client_name, client_email, total, due_date, status')
      .single();

    if (error) throw error;

    // Fire-and-forget audit log
    await logAuditEvent({
      user_id: auth.user.id,
      user_name: auth.user.name,
      action: 'update',
      resource_type: 'invoice',
      resource_id: invoiceId as string,
      details: { updatedFields: Object.keys(updates), newStatus: status },
      ip_address: getClientIP(request),
    });

    // Notify client on status changes
    if (status && invoice) {
      const clientId = invoice.client_id as string;
      const invoiceStatus = status as string;

      if (clientId && (invoiceStatus === 'sent' || invoiceStatus === 'paid' || invoiceStatus === 'overdue')) {
        // In-app notification
        const notifTitles: Record<string, string> = {
          sent: 'New invoice available',
          paid: 'Payment confirmed',
          overdue: 'Invoice payment overdue',
        };
        notifyClient(clientId, {
          type: invoiceStatus === 'sent' ? 'invoice_sent' : invoiceStatus === 'overdue' ? 'invoice_overdue' : 'invoice_created',
          title: notifTitles[invoiceStatus],
          message: `Invoice ${invoice.invoice_number} — ${invoice.client_name}`,
          priority: invoiceStatus === 'paid' ? 'normal' : 'high',
          actionUrl: `/client/${clientId}/documents`,
        });

        // Email the client for sent and overdue
        if ((invoiceStatus === 'sent' || invoiceStatus === 'overdue') && invoice.client_email) {
          const emailData = invoiceStatusEmail({
            invoiceNumber: invoice.invoice_number as string,
            clientName: (invoice.client_name as string) || 'Client',
            total: Number(invoice.total) || 0,
            dueDate: invoice.due_date as string | undefined,
            status: invoiceStatus as 'sent' | 'overdue',
          });
          notifyRecipient(invoice.client_email as string, emailData.subject, emailData.html);
        }
      }
    }

    return NextResponse.json({
      success: true,
      message: 'Invoice updated successfully',
    });
  } catch (error) {
    console.error('Error updating invoice:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to update invoice' },
      { status: 500 },
    );
  }
}

// ---------------------------------------------------------------------------
// DELETE - Remove an invoice
// ---------------------------------------------------------------------------

export async function DELETE(request: NextRequest) {
  const auth = await requirePermission(request, 'finance.delete');
  if ('error' in auth) return auth.error;

  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');

    if (!id) {
      return NextResponse.json(
        { success: false, error: 'Invoice ID is required' },
        { status: 400 },
      );
    }

    const supabase = getSupabaseAdmin();
    const { error } = await supabase.from('invoices').delete().eq('id', id);

    if (error) throw error;

    // Fire-and-forget audit log
    await logAuditEvent({
      user_id: auth.user.id,
      user_name: auth.user.name,
      action: 'delete',
      resource_type: 'invoice',
      resource_id: id,
      details: {},
      ip_address: getClientIP(request),
    });

    return NextResponse.json({
      success: true,
      message: 'Invoice deleted successfully',
    });
  } catch (error) {
    console.error('Error deleting invoice:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to delete invoice' },
      { status: 500 },
    );
  }
}
