import type { LeadRow } from '@/lib/sales/types';

export function leadRow(overrides: Partial<LeadRow> = {}): LeadRow {
  return {
    id: 'lead_1',
    name: 'Priya Shah',
    email: 'priya@example.com',
    phone: '98332 57659',
    phone_e164: '+919833257659',
    company: 'Acme',
    website: null,
    job_title: null,
    company_size: null,
    industry: null,
    project_type: null,
    project_description: 'Need more qualified leads',
    budget_range: null,
    timeline: null,
    primary_challenge: null,
    status: 'new',
    priority: 'warm',
    source: 'website_form',
    source_detail: null,
    external_source_id: null,
    lead_score: 50,
    owner_id: 'user-1',
    assigned_to: 'Asha',
    custom_fields: {},
    tags: [],
    consent_basis: 'inbound_request',
    sequence_key: null,
    sequence_step: null,
    sequence_status: null,
    sequence_stop_reason: null,
    first_response_at: null,
    last_activity_at: null,
    deal_value: null,
    currency: null,
    lost_reason: null,
    client_id: null,
    created_at: '2026-09-15T04:00:00.000Z',
    updated_at: null,
    ...overrides,
  };
}
