/**
 * Invoice Management Page
 * List, filter, search, and manage all invoices.
 */

'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import { createPortal } from 'react-dom';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import {
  FileText,
  Plus,
  Search,
  Filter,
  Download,
  Eye,
  Copy,
  MoreHorizontal,
  IndianRupee,
  Clock,
  CheckCircle2,
  AlertCircle,
  Send,
  Trash2,
  RefreshCw,
  Pencil,
} from 'lucide-react';
import {
  DashboardCard as Card,
  CardContent,
  CardHeader,
  CardTitle,
  DashboardButton,
  MetricCard,
} from '@/design-system';
import { Badge } from '@/components/ui/Badge';
import { PageHeader } from '@/components/ui/page-header';
import { StatusBadge } from '@/components/ui/status-badge';
import { EmptyState } from '@/components/ui/empty-state';
import { Skeleton } from '@/components/ui/skeleton';
import { Input } from '@/components/ui/Input';
import { Select } from '@/components/ui/select-native';
import { adminToast } from '@/lib/admin/toast';
import { ConfirmDialog } from '@/components/admin/ConfirmDialog';
import type { SimplePDFGenerator } from '@/lib/admin/pdf-simple';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface InvoiceListItem {
  id: string;
  invoiceNumber: string;
  date: string;
  dueDate: string;
  client: {
    id: string;
    name: string;
    email: string;
    phone: string;
    address: string;
    city: string;
    state: string;
    country: string;
    gstNumber: string;
  };
  lineItems: Array<{
    description: string;
    quantity: number;
    rate: number;
    amount: number;
  }>;
  subtotal: number;
  taxRate: number;
  taxAmount: number;
  total: number;
  notes: string;
  terms: string;
  status: 'draft' | 'sent' | 'paid' | 'overdue' | 'cancelled';
  autoGenerated?: boolean;
  createdAt: string;
  updatedAt: string;
}

interface InvoiceStats {
  total: number;
  draft: number;
  sent: number;
  paid: number;
  overdue: number;
  totalOutstanding: number;
  totalPaid: number;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const fmt = (n: number) => `₹${n.toLocaleString('en-IN')}`;

const fmtDate = (d: string) =>
  new Date(d).toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function InvoicesPage() {
  const router = useRouter();
  const [invoices, setInvoices] = useState<InvoiceListItem[]>([]);
  const [stats, setStats] = useState<InvoiceStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [openMenu, setOpenMenu] = useState<string | null>(null);
  const pdfGeneratorRef = useRef<SimplePDFGenerator | null>(null);
  const getPdfGenerator = async () => {
    if (!pdfGeneratorRef.current) {
      const { SimplePDFGenerator } = await import('@/lib/admin/pdf-simple');
      pdfGeneratorRef.current = new SimplePDFGenerator();
    }
    return pdfGeneratorRef.current;
  };
  const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);
  const menuBtnRefs = useRef<Record<string, HTMLButtonElement | null>>({});

  // ---- Fetch invoices ----
  const fetchInvoices = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (searchQuery) params.set('search', searchQuery);
      if (statusFilter !== 'all') params.set('status', statusFilter);

      const res = await fetch(`/api/invoices?${params}`);
      const result = await res.json();

      if (result.success) {
        setInvoices(result.data);
        setStats(result.stats);
      } else {
        adminToast.error('Failed to load invoices');
      }
    } catch {
      adminToast.error('Error connecting to server');
    } finally {
      setLoading(false);
    }
  }, [searchQuery, statusFilter]);

  useEffect(() => {
    fetchInvoices();
  }, [fetchInvoices]);

  // ---- Actions ----
  const updateStatus = async (invoiceId: string, status: string) => {
    try {
      const res = await fetch('/api/invoices', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ invoiceId, status }),
      });
      const result = await res.json();
      if (result.success) {
        adminToast.success(`Invoice marked as ${status}`);
        fetchInvoices();
      } else {
        adminToast.error('Failed to update status');
      }
    } catch {
      adminToast.error('Error updating invoice');
    }
    setOpenMenu(null);
  };

  const deleteInvoice = async (id: string) => {
    try {
      const res = await fetch(`/api/invoices?id=${id}`, { method: 'DELETE' });
      const result = await res.json();
      if (result.success) {
        adminToast.success('Invoice deleted');
        fetchInvoices();
      } else {
        adminToast.error('Failed to delete invoice');
      }
    } catch {
      adminToast.error('Error deleting invoice');
    }
    setOpenMenu(null);
  };

  const downloadPDF = async (invoice: InvoiceListItem) => {
    try {
      const { SimplePDFGenerator } = await import('@/lib/admin/pdf-simple');
      const defaultName = SimplePDFGenerator.getDefaultFilename(invoice);
      const customName = window.prompt('Filename for the PDF:', defaultName);
      if (customName === null) return; // User cancelled
      const gen = await getPdfGenerator();
      await gen.downloadPDF(invoice as any, customName || defaultName);
    } catch {
      adminToast.error('Error downloading PDF');
    }
  };

  const previewPDF = async (invoice: InvoiceListItem) => {
    try {
      const gen = await getPdfGenerator();
      const uri = await gen.generateInvoice(invoice as any);
      const win = window.open('', '_blank');
      if (win) {
        win.document.write(
          `<html><body style="margin:0"><embed src="${uri}" width="100%" height="100%" type="application/pdf"></body></html>`,
        );
      }
    } catch {
      adminToast.error('Error generating preview');
    }
  };

  // ---- Render ----
  return (
    <div className="space-y-4 sm:space-y-6">
      <PageHeader
        title="Invoices"
        description="Manage and track all your invoices."
        actions={
          <Link href="/admin/invoice">
            <DashboardButton variant="primary" size="sm">
              <Plus className="w-4 h-4" />
              New Invoice
            </DashboardButton>
          </Link>
        }
      />

      {/* Summary cards */}
      {stats && (
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-4">
          <MetricCard
            title="Total Invoices"
            value={String(stats.total)}
            subtitle={`${stats.draft} drafts`}
            icon={<FileText className="w-5 h-5" />}
            variant="admin"
          />
          <MetricCard
            title="Outstanding"
            value={fmt(stats.totalOutstanding)}
            subtitle={`${stats.sent + stats.overdue} invoices`}
            icon={<Clock className="w-5 h-5" />}
            variant="admin"
          />
          <MetricCard
            title="Paid"
            value={fmt(stats.totalPaid)}
            subtitle={`${stats.paid} invoices`}
            icon={<CheckCircle2 className="w-5 h-5" />}
            variant="admin"
          />
          <MetricCard
            title="Overdue"
            value={String(stats.overdue)}
            subtitle={stats.overdue > 0 ? 'Needs attention' : 'All clear'}
            icon={<AlertCircle className="w-5 h-5" />}
            variant="admin"
          />
        </div>
      )}

      {/* Filters */}
      <Card variant="admin">
        <CardContent className="p-4">
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
            {/* Search */}
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-fm-neutral-400" />
              <Input
                type="text"
                placeholder="Search by invoice # or client..."
                value={searchQuery}
                onChange={e => setSearchQuery(e.target.value)}
                className="pl-9"
              />
            </div>

            {/* Status filter */}
            <div className="flex items-center gap-2">
              <Filter className="w-4 h-4 text-fm-neutral-500" />
              <Select
                value={statusFilter}
                onChange={e => setStatusFilter(e.target.value)}
              >
                <option value="all">All Status</option>
                <option value="draft">Draft</option>
                <option value="sent">Sent</option>
                <option value="paid">Paid</option>
                <option value="overdue">Overdue</option>
                <option value="cancelled">Cancelled</option>
              </Select>
            </div>

            <DashboardButton variant="ghost" size="sm" onClick={fetchInvoices}>
              <RefreshCw className="w-4 h-4" />
            </DashboardButton>
          </div>
        </CardContent>
      </Card>

      {/* Invoice table */}
      <Card variant="admin">
        <CardContent className="p-0">
          {loading ? (
            <div className="p-4 sm:p-6 space-y-4">
              {[1, 2, 3, 4].map((i) => (
                <div key={i} className="flex items-center gap-4">
                  <Skeleton className="h-5 w-24" />
                  <Skeleton className="h-5 w-32 flex-1" />
                  <Skeleton className="h-5 w-20" />
                  <Skeleton className="h-5 w-20" />
                  <Skeleton className="h-5 w-24" />
                  <Skeleton className="h-6 w-16 rounded-full" />
                  <Skeleton className="h-5 w-16" />
                </div>
              ))}
            </div>
          ) : invoices.length === 0 ? (
            <EmptyState
              icon={<FileText className="w-6 h-6" />}
              title="No invoices found"
              description={
                searchQuery || statusFilter !== 'all'
                  ? 'Try adjusting your filters.'
                  : 'Create your first invoice to get started.'
              }
              action={
                <Link href="/admin/invoice">
                  <DashboardButton variant="primary" size="sm">
                    <Plus className="w-4 h-4" />
                    Create Invoice
                  </DashboardButton>
                </Link>
              }
            />
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-fm-neutral-200 bg-fm-neutral-50">
                    <th className="text-left py-3 px-4 font-medium text-fm-neutral-600">
                      Invoice
                    </th>
                    <th className="text-left py-3 px-4 font-medium text-fm-neutral-600">
                      Client
                    </th>
                    <th className="text-left py-3 px-4 font-medium text-fm-neutral-600 hidden md:table-cell">
                      Date
                    </th>
                    <th className="text-left py-3 px-4 font-medium text-fm-neutral-600 hidden lg:table-cell">
                      Due Date
                    </th>
                    <th className="text-right py-3 px-4 font-medium text-fm-neutral-600">
                      Amount
                    </th>
                    <th className="text-center py-3 px-4 font-medium text-fm-neutral-600">
                      Status
                    </th>
                    <th className="text-right py-3 px-4 font-medium text-fm-neutral-600">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {invoices.map(inv => {
                    return (
                      <tr
                        key={inv.id}
                        className="border-b border-fm-neutral-100 hover:bg-fm-neutral-50 transition-colors"
                      >
                        {/* Invoice # */}
                        <td className="py-3 px-4">
                          <span className="font-semibold text-fm-magenta-600 truncate max-w-[120px] inline-block">
                            #{inv.invoiceNumber}
                          </span>
                          {inv.autoGenerated && (
                            <span className="ml-1.5 inline-flex items-center text-[10px] font-bold px-1.5 py-0.5 rounded bg-violet-50 text-violet-700 border border-violet-200">
                              Auto
                            </span>
                          )}
                        </td>

                        {/* Client */}
                        <td className="py-3 px-4 max-w-[180px]">
                          <p className="font-medium text-fm-neutral-900 truncate">
                            {inv.client?.name || '—'}
                          </p>
                          <p className="text-xs text-fm-neutral-500 truncate">
                            {inv.client?.email || ''}
                          </p>
                        </td>

                        {/* Date */}
                        <td className="py-3 px-4 hidden md:table-cell text-fm-neutral-600">
                          {fmtDate(inv.date)}
                        </td>

                        {/* Due Date */}
                        <td className="py-3 px-4 hidden lg:table-cell text-fm-neutral-600">
                          {fmtDate(inv.dueDate)}
                        </td>

                        {/* Amount */}
                        <td className="py-3 px-4 text-right font-semibold text-fm-neutral-900">
                          {fmt(inv.total)}
                        </td>

                        {/* Status */}
                        <td className="py-3 px-4">
                          <div className="flex justify-center">
                            <StatusBadge status={inv.status} />
                          </div>
                        </td>

                        {/* Actions */}
                        <td className="py-3 px-4">
                          <div className="flex items-center justify-end gap-1 relative">
                            <button
                              onClick={() => previewPDF(inv)}
                              className="p-1.5 rounded hover:bg-fm-neutral-100 text-fm-neutral-500 hover:text-fm-neutral-700"
                              title="Preview PDF"
                            >
                              <Eye className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => downloadPDF(inv)}
                              className="p-1.5 rounded hover:bg-fm-neutral-100 text-fm-neutral-500 hover:text-fm-neutral-700"
                              title="Download PDF"
                            >
                              <Download className="w-4 h-4" />
                            </button>

                            {/* More menu */}
                            <button
                              ref={el => { menuBtnRefs.current[inv.id] = el; }}
                              onClick={() =>
                                setOpenMenu(
                                  openMenu === inv.id ? null : inv.id,
                                )
                              }
                              className="p-1.5 rounded hover:bg-fm-neutral-100 text-fm-neutral-500 hover:text-fm-neutral-700"
                            >
                              <MoreHorizontal className="w-4 h-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>

      <ConfirmDialog
        open={!!deleteConfirm}
        title="Delete Invoice"
        description="Are you sure you want to delete this invoice? This action cannot be undone."
        confirmLabel="Delete"
        variant="destructive"
        onConfirm={() => {
          if (deleteConfirm) deleteInvoice(deleteConfirm);
          setDeleteConfirm(null);
        }}
        onCancel={() => setDeleteConfirm(null)}
      />

      {/* Portal-rendered dropdown — avoids overflow clipping from Card/table */}
      {openMenu && typeof document !== 'undefined' &&
        createPortal(
          <InvoiceActionMenu
            invoice={invoices.find(i => i.id === openMenu)!}
            anchorEl={menuBtnRefs.current[openMenu]}
            onClose={() => setOpenMenu(null)}
            onEdit={(id) => {
              setOpenMenu(null);
              router.push(`/admin/invoice?edit=${id}`);
            }}
            onDuplicate={(id) => {
              setOpenMenu(null);
              router.push(`/admin/invoice?duplicate=${id}`);
            }}
            onStatusChange={(id, status) => updateStatus(id, status)}
            onDelete={(id) => {
              setOpenMenu(null);
              setDeleteConfirm(id);
            }}
          />,
          document.body,
        )
      }
    </div>
  );
}

// ---------------------------------------------------------------------------
// Portal-based action menu (renders outside Card overflow)
// ---------------------------------------------------------------------------

function InvoiceActionMenu({
  invoice,
  anchorEl,
  onClose,
  onEdit,
  onDuplicate,
  onStatusChange,
  onDelete,
}: {
  invoice: InvoiceListItem;
  anchorEl: HTMLButtonElement | null;
  onClose: () => void;
  onEdit: (id: string) => void;
  onDuplicate: (id: string) => void;
  onStatusChange: (id: string, status: string) => void;
  onDelete: (id: string) => void;
}) {
  if (!invoice || !anchorEl) return null;

  const rect = anchorEl.getBoundingClientRect();
  const menuWidth = 192; // w-48
  // Position below the button, right-aligned
  let top = rect.bottom + 4;
  let left = rect.right - menuWidth;

  // Keep within viewport bounds
  if (left < 8) left = 8;
  if (top + 300 > window.innerHeight) top = rect.top - 8; // flip above if near bottom

  return (
    <>
      <div className="fixed inset-0" style={{ zIndex: 9998 }} onClick={onClose} />
      <div
        className="fixed w-48 bg-white rounded-lg shadow-lg border border-fm-neutral-200 py-1"
        style={{ zIndex: 9999, top, left }}
      >
        {/* Edit — always available */}
        <MenuBtn
          icon={<Pencil className="w-4 h-4" />}
          label="Edit Invoice"
          onClick={() => onEdit(invoice.id)}
        />

        {/* Status transitions */}
        {invoice.status === 'draft' && (
          <MenuBtn
            icon={<Send className="w-4 h-4" />}
            label="Mark as Sent"
            onClick={() => onStatusChange(invoice.id, 'sent')}
          />
        )}
        {(invoice.status === 'sent' || invoice.status === 'overdue') && (
          <MenuBtn
            icon={<CheckCircle2 className="w-4 h-4" />}
            label="Mark as Paid"
            onClick={() => onStatusChange(invoice.id, 'paid')}
          />
        )}
        {invoice.status === 'sent' && (
          <MenuBtn
            icon={<AlertCircle className="w-4 h-4" />}
            label="Mark as Overdue"
            onClick={() => onStatusChange(invoice.id, 'overdue')}
          />
        )}

        <MenuBtn
          icon={<Copy className="w-4 h-4" />}
          label="Duplicate"
          onClick={() => onDuplicate(invoice.id)}
        />

        <div className="border-t border-fm-neutral-100 my-1" />
        <MenuBtn
          icon={<Trash2 className="w-4 h-4 text-red-500" />}
          label="Delete"
          onClick={() => onDelete(invoice.id)}
          danger
        />
      </div>
    </>
  );
}

// ---------------------------------------------------------------------------
// Menu button helper
// ---------------------------------------------------------------------------

function MenuBtn({
  icon,
  label,
  onClick,
  danger,
}: {
  icon: React.ReactNode;
  label: string;
  onClick: () => void;
  danger?: boolean;
}) {
  return (
    <button
      onClick={onClick}
      className={`w-full flex items-center gap-2 px-3 py-2 text-sm hover:bg-fm-neutral-50 ${
        danger
          ? 'text-red-600 hover:bg-red-50'
          : 'text-fm-neutral-700'
      }`}
    >
      {icon}
      {label}
    </button>
  );
}
