-- Add auto-invoice fields to clients table
ALTER TABLE clients ADD COLUMN IF NOT EXISTS auto_invoice boolean DEFAULT false;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS auto_invoice_day integer DEFAULT 1;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS auto_invoice_send boolean DEFAULT false;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS auto_invoice_template jsonb DEFAULT '[]'::jsonb;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS auto_invoice_currency varchar DEFAULT 'INR';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS auto_invoice_tax_rate numeric DEFAULT 18;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS auto_invoice_notes text;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS auto_invoice_terms text;

-- Add auto_generated flag to invoices table
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS auto_generated boolean DEFAULT false;

COMMENT ON COLUMN clients.auto_invoice IS 'Enable automatic monthly invoice generation';
COMMENT ON COLUMN clients.auto_invoice_day IS 'Day of month to generate invoice (1-28)';
COMMENT ON COLUMN clients.auto_invoice_send IS 'Auto-send invoice to client (true) or save as draft (false)';
COMMENT ON COLUMN clients.auto_invoice_template IS 'JSON array of line items template for auto-generated invoices';
COMMENT ON COLUMN invoices.auto_generated IS 'Whether this invoice was auto-generated by the system';
